[package]
name = "gridworld"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]
edition = "2018"
publish = false

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
schemars = "0.6"

[dependencies.toybox-core]
version = "*"
path = "../core"
